### PR TITLE
cache search form submitting

### PR DESCRIPTION
**Pull request by coburncoburn**
a simple way to add a cache to the library's document requests, the basic cache that is in the library would eventually use too much memory and become a bottleneck as it resides in a single genserver, but there is a behaviour to write an adapter for another cache ( or of course it is possible to improve the built in cache )

### CODE REVIEW

**Review by ghbutton — APPROVED** [review]

**Review by gthiruva — APPROVED** [review]

**Review by newtrat — COMMENTED** [review]
I like this idea, but we can't merge this as-is, right? Cached values are never deleted, only replaced, so the cache will eat more and more memory over time, just as Coburn says. It grows any time anyone requests a new search form.

**Comment by desmondgee** [comment]
@newtrat There is a ttl hardcoded to 60 seconds here - https://github.com/TheRealReal/prismic-elixir/blob/master/lib/cache.ex#L33

We might want to make this more flexible per endpoint somehow.

**Comment by newtrat** [comment]
@desmondgee Yes, the ttl is 60 seconds, but we only check for cache expiration when a new request is made for the expired content. So nothing is ever removed from the cache for any length of time -- the most that happens is it gets removed for a little bit (when the new request comes in and sees that it's expired), then immediately gets reinstated (when that new request figures out what the new value should be).

**Comment by desmondgee** [comment]
@newtrat Oh yah. I see what you mean now. Yah. That needs to be fixed. Or swapped out with another caching library. Building caching into the api instead is another option.

**Comment by whitfin** [comment]
@coburncoburn not to plug my own library here, but have you considered using [cachex](https://github.com/whitfin/cachex)? I'm happy to add an adapter for it in this codebase (or tweak the default to use it, if you prefer that instead).

**Comment by newtrat** [comment]
Hi @whitfin, I think we use cachex on some of our other Elixir projects, so your suggestion's definitely welcome 🙂

I think the reason we haven't looked more at this PR is that we've decided for now that this caching should be the responsibility of the client using this library, rather than of the library itself. Definitely worth looking into if we come back to doing caching here, though. What do you think @desmondgee ? Is this PR still on our radar?

**Comment by desmondgee** [comment]
@newtrat We have pushed work on caching back a bit. I agree, cachex seems worth looking into. I'll make a note of it on the ticket. Thanks for the plug @whitfin.

**Pull request closed without merging**
